#! /usr/bin/env bash

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
picom --config ~/.config/picom/picom.conf &
pkill dunst; dunst &
wal -R &
sh /home/arik/.config/polybar/launch.sh &
sh /home/arik/dotfiles/bspwm/.config/scripts/startup-stuff.sh &
lxpolkit &
xinput set-prop "ETPS/2 Elantech Touchpad" "libinput Tapping Enabled" 1 &
dex --autostart --environment i3 &


# Workspaces
bspc monitor -d I II III IV V VI VII VIII IX X

# Stuff
bspc config border_width         0
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer   true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
